# Form implementation generated from reading ui file 'giaoDien1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
import numpy as np
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QImage, QPixmap 
from PyQt6.QtWidgets import QApplication, QGraphicsView, QGraphicsScene, QGraphicsPixmapItem, QMainWindow, QVBoxLayout, QWidget
import sys
import findContours

vt = 0
class Ui_MainWindow(object):   
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 570)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 93, 61))
        self.pushButton.setObjectName("pushButton")
        
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 50, 471, 351))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setLineWidth(3)
        self.label.setText("")
        #self.label.setPixmap(QtGui.QPixmap("d:\\Projects_Python\\findContours\\giaoDien\\../img/img1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 230, 104, 61))
        self.textEdit.setObjectName("textEdit")
        
        self.text = QtWidgets.QLabel(parent=self.centralwidget)
        self.text.setGeometry(QtCore.QRect(40, 500, 300, 20))
        self.text.setSizeIncrement(QtCore.QSize(0, 0))
        self.text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.text.setLineWidth(1)
        self.text.setText("")
        #self.label.setPixmap(QtGui.QPixmap("d:\\Projects_Python\\findContours\\giaoDien\\../img/img1.png"))
        self.text.setScaledContents(True)
        self.text.setObjectName("text")
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #========================================================================
        #handle 
        
        self.pushButton.clicked.connect(self.handler)
        #=================  
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.label.setText(_translate("MainWindow", "Image"))


#==================Xu Ly O Day=================================================================
        
    def handler(self):
        print("hello worrld")
        textImg = self.label.text()
        
        if(self.textEdit.toPlainText() != ''):
            vt = int(self.textEdit.toPlainText())
            if(vt >= 0):
                findContours.main(vt)
            else:
                print('hi')
                self.text.setText('HÃY NHẬP SỐ TỪ 0-5')
        else:
            self.text.setText('Đừng bỏ trống')
            
        self.label.setText('hello')
        self.label.setPixmap(QPixmap("d:\\Projects_Python\\findContours\\giaoDien\\../img/img_1.png"))
        
        
#main==================================
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
